#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=16gb,walltime=02:00:00
#PBS -N BROCCOLI
#PBS -V

set -e
set -x

mkdir -p output

#convert input into bids
bl2bids

sub=$(jq -r "._inputs[0].meta.subject" config.json | tr -d "_")
if [[ -z $sub || $sub == null ]]; then
    sub=0
fi

taskname=$(jq -r '._inputs[] | select(.id == "fmri") | .meta.task' config.json)
echo "task: $taskname"

mkdir -p regress
bold_json=$(find bids/sub-${sub}/func -name "*_bold.json")
[[ -f $bold_json ]] && cp $bold_json bids/task-${taskname}_bold.json

time singularity run --nv -e \
  -B `pwd`/bids:/bids \
  -B `pwd`/output:/output \
  docker://bids/broccoli:v1.0.0 \
  /bids /output participant --participant_label $sub

tscores=output/sub-${sub}/rhymejudgment/sub-${sub}_tscores_contrast0001_MNI.nii

singularity exec -e docker://brainlife/fsl:6.0.4 fslmaths $tscores -thr 5 output/sub-${sub}/activation_map_MNI.nii.gz

mkdir -p map
cp output/sub-${sub}/activation_map_MNI.nii.gz map/mask.nii.gz #temporary mask datatype
